export const GET_PROJECTS_DATA: "GET_PROJECTS_DATA" = "GET_PROJECTS_DATA";
export const GET_PROJECTS_DATA_FAILED: "GET_PROJECTS_DATA_FAILED" =
  "GET_PROJECTS_DATA_FAILED";
export const GET_PROJECTS_DATA_SUCCESS: "GET_PROJECTS_DATA_SUCCESS" =
  "GET_PROJECTS_DATA_SUCCESS";
export const GET_PROJECT_DATA: "GET_PROJECT_DATA" = "GET_PROJECT_DATA";
export const GET_PROJECT_DATA_FAILED: "GET_PROJECT_DATA_FAILED" =
  "GET_PROJECT_DATA_FAILED";
export const GET_PROJECT_DATA_SUCCESS: "GET_PROJECT_DATA_SUCCESS" =
  "GET_PROJECT_DATA_SUCCESS";
export const CREATE_PROJECT_DATA: "CREATE_PROJECT_DATA" = "CREATE_PROJECT_DATA";
export const CREATE_PROJECT_FAILED: "CREATE_PROJECT_FAILED" =
  "CREATE_PROJECT_FAILED";
export const CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS" =
  "CREATE_PROJECT_SUCCESS";
export const DELETE_AFTER_CREATION: "DELETE_AFTER_CREATION" =
  "DELETE_AFTER_CREATION";
export const CREATE_TASK_DATA: "CREATE_TASK_DATA" = "CREATE_TASK_DATA";
export const CREATE_TASK_FAILED: "CREATE_TASK_FAILED" = "CREATE_TASK_FAILED";
export const CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS" = "CREATE_TASK_SUCCESS";
